package consts

var (
	BadRequest         = "data can't be processed"
	UnAuthorized       = "not authorized"
	ValidationErr      = "err while validating"
	ProductCreated     = "Product created Successfully"
	DeleteUnsuccessful = "Could not delete the product"
	DeleteSuccessful   = "Delete Successful"
	AddedToCart        = "Product successfully added to cart"
	EmptyCart          = "Cart is empty"
	ParseErr           = "Invalid format of data"
	CartItemRemoved    = "Cart item removed successfully"
	SignUpSuccessful   = "Successfully Signed Up!!"
	SignUpUnSuccessful = "SignUp Failed :("
	IncorerctDetails   = "email or password incorrect"
	ProductExists      = "Product already exists"
	ProductNotCreated  = "Product Not created"
	InvalidID          = "Invalid id"
	CartUpdateFailed   = "could not update cart item"
	FailedToAddItem    = "could not add product to cart"
	CartItemNotFound   = "cart item not found"
	RemoveUnsuccessful = "Could not remove cart item"
	InvalidCartID      = "Cart item does not belong to the logged in user"
	PreloadErr         = "Error while Preloading"
	DuplicateUser      = "User already exists"
	TokenGenErr        = "Error Creating JWT token"
	CartCreationErr    = "could not create/found the cart"
)
